### ISSUE TITLE
whats next?

### ISSUE THREAD

**Issue by pyk** [idjs/belajar-nodejs#1]
gan ane pengen berkontribusi nih, ane interest banget ke nodeJS. apa yang bisa saya lakukan gan? mungkin ada semacam **TODO-LIST** untuk repo ini yang belum selesai kemudian bisa saya bantu untuk menselesaikan.

ane juga punya saran nih gan, ane lihat di [http://idjs.github.io/belajar-nodejs/](http://idjs.github.io/belajar-nodejs/) kontennya cuman pengenalan aja, gak lengkap kaya [Readme](https://github.com/idjs/belajar-nodejs/blob/gh-pages/README.md) filenya. siapa tau ane bisa bantu ngeorganisir lagi di [index.html](https://github.com/idjs/belajar-nodejs/blob/gh-pages/index.html) biar bisa di akses lewat [http://idjs.github.io/belajar-nodejs/](http://idjs.github.io/belajar-nodejs/) maupun langsung di reponya(readme).

dengan senang hati gan, 
bayu

**Comment by raitucarp** [comment]
langsung fork aja terus pull, ntar dimerge disini

**Comment by pyk** [comment]
oke gan thanks :+1:
