### ISSUE TITLE
Cara Eksekusi File Node.js

### ISSUE THREAD

**Issue by furqanalfath** [idjs/belajar-nodejs#3]
Mas, saya mau tanya. Saya sudah bisa jalanin nodejs server.js dan index.html.

Saya punya file nodejs misalkan tes.js ya. Kan kalo kita mau run dari npm tinggal ketik "node tes.js". Nah, saya pengen eksekusinya dari browser, jadi ada tombol yang kalo di click akan run si tes.js. Itu cara terbaiknya gimana? Saya pakai index.html katanya ga bisa kalo mau eksekusi kayak gitu. Jadi cara terbaiknya pakai apa ya di sisi browsernya?

**Comment by tianp** [comment]
Halo mas @malvouz,

Mungkin perlu sedikit lebih dipahami antara server-side dan client-side javascript. Kalau isi dari `tes.js` adalah server-side code, maka tidak bisa dieksekusi di browser (client-side). Untuk lebih yakin, apa bisa di-share isi dari `tes.js` tsb?

**Comment by furqanalfath** [comment]
@tianp 

kalo codingnya gini server side ya? Bedanya apa sama client side? Apakah client side itu yang model jquery, dan javascrit biasa (tanpa node.js)?

ini isi `tes.js` , jadi saya mau run `tes.js` lewat index.html tanpa ketik node tes.js di command.

```
var PORT = 33333;
var HOST = '192.168.100.30';

var dgram = require('dgram');
var message = new Buffer('2');

var client = dgram.createSocket('udp4');
client.send(message, 0, message.length, PORT, HOST, function(err, bytes) {
    if (err) throw err;
    console.log('UDP message sent to ' + HOST +':'+ PORT);
    client.close();
});
```

ini isi `server.js`

```
var PORT = 33333;
var HOST = '192.168.100.50';

var dgram = require('dgram');
var server = dgram.createSocket('udp4');

server.on('listening', function () {
    var address = server.address();
    console.log('UDP Server listening on ' + address.address + ":" + address.port);
});

server.on('message', function (message, remote) {
    console.log(remote.address + ':' + remote.port +' - ' + message);

});

server.bind(PORT, HOST);
```

**Comment by tianp** [comment]
I see, `tes.js` adalah UDP Client namun tetap harus berjalan di sisi server. Kalau memang goal nya adalah mengirimkan UDP message dari browser, saran saya:
1. Buat AJAX yang di-trigger oleh button di HTML yang bisa diakses browser.
2. Request AJAX tsb diterima oleh `tes.js` (UDP Client) yang berjalan di server
3. UDP Client mengirimkan message ke UDP server

**Comment by furqanalfath** [comment]
@tianp 

 saya fikirnya bisa di eksekusi dengan mudah, ternyata harus bikin model ajax lagi. saya kepikiran pakai `socket.io`. oke makasih ya mas.

**Comment by raitucarp** [comment]
Bayangkan node.js itu seperti PHP atau python, atau ruby mas. Tapi dalam bahasa javascript

Kalau boleh tahu dapat contoh kodenya (tes.js) dari mana mas @malvouz?

**Comment by furqanalfath** [comment]
@raitucarp 

dapet dari temen saya. memang kenapa mas?

dia bisa bikin button di browser terus jalanin si `node tes.js` dengan klik.
saya yakinnya dia make `socket.io`, belum sempet nanya.

**Comment by tianp** [comment]
Oh ya, `socket.io` make sense 👍

**Comment by furqanalfath** [comment]
buat info aja, saya sudah coba `socket.io` dan berhasil untuk eksekusi dari browser.
