### ISSUE TITLE
Ga bisa download versi PDF

### ISSUE THREAD

**Issue by ndunks** [idjs/belajar-nodejs#5]
![image](https://user-images.githubusercontent.com/5500313/63238470-deb46200-c270-11e9-984d-4ca44312cbe6.png)

**Comment by junwatu** [comment]
Karena Gitbook sudah berubah platform sehingga tidak menyediakan lagi PDF, Epub maupun Mobi tetapi anda masih bisa men-download versi PDF melalui link dibawah ini.


📖 **[Download PDF Belajar Node.js](https://github.com/idjs/belajar-nodejs/blob/gh-pages/belajar_node.js.pdf)**

@ndunks Trims sudah fill issue 😄

**Comment by ndunks** [comment]
Thanks bro..
